#define IDI_MAIN		1

#define IDB_SETTINGS	10
#define IDB_LOG_ICONS	11
#define IDB_SPACE_ICONS	12

#define ID_PNG_LOGO		19

#define IDM_MAIN		20
#define IDM_TASK		21
#define IDM_TRAY		22

#define IDD_ABOUT						50
#define IDD_MESSAGE						51
#define IDD_SETTINGS					52
#define IDD_SETTINGS_GENERAL			53
#define IDD_SETTINGS_STATUS_BAR			54
#define IDD_SETTINGS_INFORMATION_BAR	55
#define IDD_SETTINGS_RECORDING			56
#define IDD_SETTINGS_STREAMING			57
#define IDD_SETTINGS_TOOLS				58
#define IDD_SETTINGS_LOG				59
#define IDD_TASK_SETTINGS_GENERAL		60
#define IDD_TASK_SETTINGS_RECORDING		61
#define IDD_TASK_SETTINGS_STREAMING		62
#define IDD_LOG							70
#define IDD_CHANNEL_LIST				71
#define IDD_TASK_INFO					72
#define IDD_SEND_MESSAGE				73

#define CM_MINIMIZE					100
#define CM_CLOSE					101
#define CM_EXIT						102
#define CM_SHOW						103
#define CM_ALWAYS_ON_TOP			104
#define CM_TRANSLUCENT				105
#define CM_INFORMATION_BAR			106
#define CM_SETTINGS					110
#define CM_ABOUT					111
#define CM_NEW_TASK					120
#define CM_END_ALL_TASKS			121
#define CM_END_ALL_TASKS_AND_EXIT	122

#define CM_TASK_END					200
#define CM_TASK_TERMINATE			201
#define CM_TASK_SETTINGS			202
#define CM_TASK_LOG					203
#define CM_TASK_CHANNEL_LIST		204
#define CM_TASK_INFO				205
#define CM_TASK_SEND_MESSAGE		206

#define CM_TASK_TOOL_FIRST			2000
#define CM_TASK_TOOL_LAST			2999

#define IDC_ABOUT_LOGO				1000
#define IDC_ABOUT_VERSION			1001

#define IDC_MESSAGE_ICON			1000
#define IDC_MESSAGE_TEXT			1001
#define IDC_MESSAGE_DONT_ASK_AGAIN	1002

#define IDC_SETTINGS_LIST			1000
#define IDC_SETTINGS_TITLE			1001
#define IDC_SETTINGS_PAGE_PLACE		1002
#define IDC_SETTINGS_HELP			1003

#define IDC_SETTINGS_CONFIRM_CLOSE				1000
#define IDC_SETTINGS_CONFIRM_CLOSE_TASK_EXISTS	1001
#define IDC_SETTINGS_CONFIRM_TASK_EXIT			1002
#define IDC_SETTINGS_EXIT_WHEN_ALL_TASK_ENDED	1003
#define IDC_SETTINGS_SHOW_IN_TASKBAR			1004
#define IDC_SETTINGS_SHOW_TRAY_ICON				1005
#define IDC_SETTINGS_MINIMIZE_TO_TRAY			1006
#define IDC_SETTINGS_THEME						1010
#define IDC_SETTINGS_SAVE_DEFAULT_THEME			1011
#define IDC_SETTINGS_TRANSLUCENT_OPACITY		1012
#define IDC_SETTINGS_TSTASK_FILE_NAME			1020
#define IDC_SETTINGS_TSTASK_OPTIONS			1021

#define IDC_SETTINGS_STATUS_BAR_ITEM_LIST		1000
#define IDC_SETTINGS_STATUS_BAR_DEFAULT			1001
#define IDC_SETTINGS_STATUS_BAR_FONT_INFO		1002
#define IDC_SETTINGS_STATUS_BAR_CHOOSE_FONT		1003
#define IDC_SETTINGS_STATUS_BAR_MULTI_ROW		1004
#define IDC_SETTINGS_STATUS_BAR_MAX_ROWS		1005

#define IDC_SETTINGS_INFORMATION_BAR_ITEM_LIST				1000
#define IDC_SETTINGS_INFORMATION_BAR_NEW_ITEM				1001
#define IDC_SETTINGS_INFORMATION_BAR_DELETE_ITEM			1002
#define IDC_SETTINGS_INFORMATION_BAR_MOVE_UP_ITEM			1003
#define IDC_SETTINGS_INFORMATION_BAR_MOVE_DOWN_ITEM			1004
#define IDC_SETTINGS_INFORMATION_BAR_FORMAT_LABEL			1010
#define IDC_SETTINGS_INFORMATION_BAR_FORMAT					1011
#define IDC_SETTINGS_INFORMATION_BAR_FORMAT_MENU			1012
#define IDC_SETTINGS_INFORMATION_BAR_TEXT_ALIGN_LABEL		1013
#define IDC_SETTINGS_INFORMATION_BAR_TEXT_ALIGN				1014
#define IDC_SETTINGS_INFORMATION_BAR_ITEM_WIDTH_LABEL		1015
#define IDC_SETTINGS_INFORMATION_BAR_ITEM_WIDTH				1016
#define IDC_SETTINGS_INFORMATION_BAR_ITEM_WIDTH_SPIN		1017
#define IDC_SETTINGS_INFORMATION_BAR_FONT_INFO				1020
#define IDC_SETTINGS_INFORMATION_BAR_CHOOSE_FONT			1021
#define IDC_SETTINGS_INFORMATION_BAR_UPDATE_INTERVAL		1022
#define IDC_SETTINGS_INFORMATION_BAR_SHOW_ERROR				1023
#define IDC_SETTINGS_INFORMATION_BAR_ERROR_DURATION_LABEL	1024
#define IDC_SETTINGS_INFORMATION_BAR_ERROR_DURATION			1025

#define IDC_SETTINGS_RECORDING_CONFIRM_CHANNEL_CHANGE	1000
#define IDC_SETTINGS_RECORDING_CONFIRM_EXIT				1001
#define IDC_SETTINGS_RECORDING_CONFIRM_STOP				1002

#define IDC_SETTINGS_TOOLS_LIST					1000
#define IDC_SETTINGS_TOOLS_MOVE_UP				1001
#define IDC_SETTINGS_TOOLS_MOVE_DOWN			1002
#define IDC_SETTINGS_TOOLS_DELETE				1003
#define IDC_SETTINGS_TOOLS_ADD					1004
#define IDC_SETTINGS_TOOLS_REPLACE				1005
#define IDC_SETTINGS_TOOLS_NAME					1006
#define IDC_SETTINGS_TOOLS_COMMAND				1007
#define IDC_SETTINGS_TOOLS_COMMAND_PARAMETERS	1008
#define IDC_SETTINGS_TOOLS_SHOW_COMMAND			1009
#define IDC_SETTINGS_TOOLS_TRIGGERS				1010
#define IDC_SETTINGS_TOOLS_TRIGGERS_MENU		1011
#define IDC_SETTINGS_TOOLS_SHOW_IN_MENU			1012

#define IDC_SETTINGS_LOG_LIST		1000
#define IDC_SETTINGS_LOG_CLEAR		1001
#define IDC_SETTINGS_LOG_SAVE		1002
#define IDC_SETTINGS_LOG_LEVEL		1003
#define IDC_SETTINGS_LOG_COPY		1004
#define IDC_SETTINGS_LOG_COPY_ALL	1005

#define IDC_TASK_SETTINGS_BONDRIVER_FOLDER				1000
#define IDC_TASK_SETTINGS_BONDRIVER_FOLDER_BROWSE		1001
#define IDC_TASK_SETTINGS_EXECUTE_CLIENT				1020
#define IDC_TASK_SETTINGS_CLIENT_FILE_NAME_LABEL		1021
#define IDC_TASK_SETTINGS_CLIENT_FILE_NAME				1022
#define IDC_TASK_SETTINGS_CLIENT_OPTIONS_LABEL			1023
#define IDC_TASK_SETTINGS_CLIENT_OPTIONS				1024

#define IDC_TASK_SETTINGS_RECORDING_FOLDER				1000
#define IDC_TASK_SETTINGS_RECORDING_FOLDER_BROWSE		1001
#define IDC_TASK_SETTINGS_RECORDING_FILE_NAME			1002
#define IDC_TASK_SETTINGS_RECORDING_FILE_NAME_FORMAT	1003
#define IDC_TASK_SETTINGS_RECORDING_FILE_NAME_PREVIEW	1004
#define IDC_TASK_SETTINGS_RECORDING_FOLDER_LIST			1005
#define IDC_TASK_SETTINGS_RECORDING_FOLDER_LIST_BROWSE	1006
#define IDC_TASK_SETTINGS_RECORDING_FOLDER_LIST_UP		1007
#define IDC_TASK_SETTINGS_RECORDING_FOLDER_LIST_DOWN	1008
#define IDC_TASK_SETTINGS_RECORDING_FOLDER_LIST_REMOVE	1009
#define IDC_TASK_SETTINGS_RECORDING_CURRENT_SERVICE		1010
#define IDC_TASK_SETTINGS_RECORDING_SAVE_CAPTION		1011
#define IDC_TASK_SETTINGS_RECORDING_SAVE_DATA_CARROUSEL	1012
#define IDC_TASK_SETTINGS_RECORDING_PRE_ALLOCATE		1013
#define IDC_TASK_SETTINGS_RECORDING_PRE_ALLOCATE_SIZE_LABEL	1014
#define IDC_TASK_SETTINGS_RECORDING_PRE_ALLOCATE_SIZE		1015
#define IDC_TASK_SETTINGS_RECORDING_PRE_ALLOCATE_SIZE_SPIN	1016
#define IDC_TASK_SETTINGS_RECORDING_PRE_ALLOCATE_SIZE_UNIT	1017
#define IDC_TASK_SETTINGS_RECORDING_WRITE_SIZE			1018
#define IDC_TASK_SETTINGS_RECORDING_WRITE_SIZE_SPIN		1019
#define IDC_TASK_SETTINGS_RECORDING_WRITE_SIZE_UNIT		1020

#define IDC_TASK_SETTINGS_STREAMING_PROTOCOL_UDP		1000
#define IDC_TASK_SETTINGS_STREAMING_PROTOCOL_TCP		1001
#define IDC_TASK_SETTINGS_STREAMING_ADDRESS				1002
#define IDC_TASK_SETTINGS_STREAMING_PORT				1003
#define IDC_TASK_SETTINGS_STREAMING_FIND_UNUSED_PORT	1004
#define IDC_TASK_SETTINGS_STREAMING_CURRENT_SERVICE		1005
#define IDC_TASK_SETTINGS_STREAMING_SEND_CAPTION		1006
#define IDC_TASK_SETTINGS_STREAMING_SEND_DATA_CARROUSEL	1007
#define IDC_TASK_SETTINGS_STREAMING_1SEG_ONLY			1008
#define IDC_TASK_SETTINGS_STREAMING_SEND_SIZE			1010
#define IDC_TASK_SETTINGS_STREAMING_SEND_SIZE_SPIN		1011
#define IDC_TASK_SETTINGS_STREAMING_SEND_WAIT			1012
#define IDC_TASK_SETTINGS_STREAMING_SEND_WAIT_SPIN		1013
#define IDC_TASK_SETTINGS_STREAMING_ADJUST_SEND_WAIT	1014

#define IDC_LOG_LIST				1000
#define IDC_LOG_SAVE				1001
#define IDC_LOG_COPY				1002
#define IDC_LOG_COPY_ALL			1003

#define IDC_CHANNELS_LIST			1000
#define IDC_CHANNELS_COPY_CH_TXT	1001

#define IDC_TASK_INFO_LIST			1000
#define IDC_TASK_INFO_UPDATE		1001
#define IDC_TASK_INFO_COPY			1002

#define IDC_MESSAGE_SEND_MESSAGE	1000
#define IDC_MESSAGE_CLEAR			1001
#define IDC_MESSAGE_SEND			1002
#define IDC_MESSAGE_RECEIVE_MESSAGE	1003
#define IDC_MESSAGE_BROADCAST		1004
